---
title: "Orçamento Projeto Pinball"
subtitle: "Circuitos Elétricos 2"
author:
  - Franciellen
  - Maria Clara
  - Sergio Pedro Rodrigues Oliveira
date: "`r format(Sys.time(), '%d %B %Y')`"
committee:
  name: Paulo
  position: Orientador acadêmico
lof: true
lot: true
toc-title: SUMÁRIO
output:
  odt_document: 
    number_sections: true
  html_document:
    number_sections: true
    df_print: paged
  md_document:
    number_sections: true
    variant: markdown_github
  github_document: 
  pdf_document: 
    number_sections: true
    toc: TRUE
  word_document: 
    toc: TRUE
    number_sections: true
header-includes:
  - \pagenumbering{roman} #adiciona letras romanas minusculas ao cabeçalho
  - \renewcommand{\listfigurename}{LISTA DE FIGURAS} #nome lista de figuras
  - \renewcommand{\listtablename}{LISTA DE TABELAS} #nome lista de tabelas
bibliography: RMarkdown/Bibliografia_arduino.bib
csl: RMarkdown/abnt.csl
---

\newpage

```{r Pacotes, echo=FALSE, message=FALSE, warning=FALSE}
library(knitr)
```

# PROJETO PINBALL

\pagenumbering{arabic} 
\newpage

# ORÇAMENTOS
## Orçamento Mecânico

```{r Orcamento_peças_mecânica, echo=FALSE, message=FALSE, warning=FALSE}
#data.frame
materiais_mec <- c("")
qtd_met_mec <- c("")
preco_unit_met_mec <- c("")
valor_total_mec <- c("")
orc_mec <- data.frame(materiais_mec,qtd_met_mec,preco_unit_met_mec,valor_total_mec)

#Tabela
kable(orc_mec,
      col.names = c("Peças Mecânicas", "Quantidade", "Preço unit.", "Valor Total"),
      align = "lccc",
      caption = "Orçamento dos peças mecânicas")
```

## Orçamento Dispositivos Eletrônicos

```{r Orcamento_disp_eletronicos, echo=FALSE, message=FALSE, warning=FALSE}
#data.frame
materiais_elet <- c("")
qtd_met_ele <- c("")
preco_unit_met_ele <- c("")
valor_total_disp <- c("")
orc_disp_ele <- data.frame(materiais_elet,qtd_met_ele,preco_unit_met_ele,valor_total_disp)

#Tabela
kable(orc_disp_ele,
      col.names = c("Dispositivos Eletrônicos", "Quantidade", "Preço unit.", "Valor Total"),
      align = "lccc",
      caption = "Orçamento dos dispositivos eletrônicos")
```


\newpage

# SITE DE FORNECEDORES

1. [Maker Hero](https://www.makerhero.com/)\
<https://www.makerhero.com/>


2. [Baú da Eletrônica](https://www.baudaeletronica.com.br/)\
<https://www.baudaeletronica.com.br/>

\newpage

# RESUMO

## Comparando Preços

\newpage

# CONCLUSÃO